Repository kubernetes-sigs/bom, pull requests merged in 2021-11, with the labels that each got.

#2 Init `sigs.k8s.io/bom` and add presubmits
  .golangci.yml
  dependencies.yaml
  go.mod
  go.sum
  mage.go
  magefile.go
  scripts/boilerplate/boilerplate.Dockerfile.txt
  scripts/boilerplate/boilerplate.Makefile.txt
  scripts/boilerplate/boilerplate.generatego.txt
  scripts/boilerplate/boilerplate.go.txt
  scripts/boilerplate/boilerplate.py.txt
  scripts/boilerplate/boilerplate.sh.txt
  scripts/verify-build.sh
Labels: size/XL, lgtm, approved, cncf-cla: yes

#1 Migrate in `k8s.io/release/cmd/bom` and associated packages
  cmd/bom/README.md
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/root.go
  cmd/bom/main.go
  docs/bom/418528.svg
  docs/bom/README.md
  docs/bom/cast.svg
  docs/bom/create-a-bill-of-materials.md
  docs/bom/etcd-v3.4.16.spdx
  docs/bom/generate.md
  go.mod
  go.sum
  magefile.go
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/license_unit_test.go
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/license/licensefakes/fake_reader_implementation.go
  pkg/provenance/predicate.go
  pkg/provenance/predicate_test.go
  pkg/provenance/predicate_unit_test.go
  pkg/provenance/provenance.go
  pkg/provenance/provenance_unit_test.go
  pkg/provenance/provenancefakes/fake_predicate_implementation.go
  pkg/provenance/provenancefakes/fake_statement_implementation.go
  pkg/provenance/statement.go
  pkg/provenance/statement_test.go
  pkg/provenance/statement_unit_test.go
  pkg/provenance/testdata/k8s-1.23.0-alpha.4-provenance.json
  pkg/spdx/builder.go
  pkg/spdx/builder_unit_test.go
  pkg/spdx/document.go
  pkg/spdx/file.go
  pkg/spdx/gomod.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/imageanalyzer_distroless.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/parser.go
  pkg/spdx/relationship.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_test.go
  pkg/spdx/spdx_unit_test.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: lgtm, size/XXL, approved, cncf-cla: yes

#3 Docs cleanup
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/dependabot.yml
  .gitignore
  README.md
  SECURITY
  SECURITY_CONTACTS
  cmd/bom/README.md
  docs/418528.svg
  docs/bom/README.md
  docs/bom/generate.md
  docs/cast.svg
  docs/create-a-bill-of-materials.md
  docs/etcd-v3.4.16.spdx
Labels: size/XL, lgtm, approved, cncf-cla: yes

#4 Support archives as package src, autonamespace and other improvements
  cmd/bom/cmd/generate.go
  pkg/spdx/builder.go
  pkg/spdx/file.go
  pkg/spdx/implementation.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_unit_test.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: kind/bug, kind/feature, size/XL, lgtm, kind/deprecation, kind/cleanup, approved, cncf-cla: yes
