Repository kubernetes-sigs/bom, pull requests merged in 2021-12, with the labels that each got.

#5 update docs with new install instruction
  README.md
Labels: ok-to-test, kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#12 add initial filetype support
  pkg/spdx/file.go
  pkg/spdx/file_test.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#13 Update provenance package to write SLSA v0.2 predicates
  go.mod
  go.sum
  pkg/internal/tools.go
  pkg/provenance/predicate.go
  pkg/provenance/predicate_unit_test.go
  pkg/provenance/provenance.go
  pkg/provenance/provenance_unit_test.go
  pkg/provenance/provenancefakes/fake_predicate_implementation.go
  pkg/provenance/provenancefakes/fake_statement_implementation.go
  pkg/provenance/statement.go
  pkg/provenance/statement_unit_test.go
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes
