Repository kubernetes-sigs/bom, pull requests merged in 2022-04, with the labels that each got.

#88 update build image to use latest go
  cloudbuild.yaml
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#89 update version font and ko version
  cmd/bom/cmd/root.go
  magefile.go
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#90 Add canary image promotion jobs
  canary/images/k8s-staging-bom/images.yaml
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#91 Use temporary registry location
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#92 Specify SVC account in promo manifest
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#93 Delete canary builds manifests
  canary/images/k8s-staging-bom/images.yaml
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Labels: lgtm, kind/cleanup, size/S, approved, cncf-cla: yes

#97 Bug fixes in go dependencies
  pkg/spdx/gomod.go
  pkg/spdx/implementation.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes
