Repository kubernetes-sigs/bom, pull requests merged in 2022-07, with the labels that each got.

#130 Add External Document Ref to json types
  pkg/spdx/json/v2.2.2/types.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#131 Doc deploy
  .github/workflows/docs.yml
  docs/.gitignore
  docs/README.md
  docs/assets/icons/logo.svg
  docs/assets/js/search.js
  docs/assets/scss/_base.scss
  docs/assets/scss/_case-studies.scss
  docs/assets/scss/_custom.scss
  docs/assets/scss/_desktop.scss
  docs/assets/scss/_reset.scss
  docs/assets/scss/_size.scss
  docs/assets/scss/_skin.scss
  docs/assets/scss/_tablet.scss
  docs/assets/scss/_variables_project.scss
  docs/config.toml
  docs/content/en/CLI Reference/_index.md
  docs/content/en/CLI Reference/bom_document.md
  docs/content/en/CLI Reference/bom_document_outline.md
  docs/content/en/CLI Reference/bom_document_query.md
  docs/content/en/CLI Reference/bom_generate.md
  docs/content/en/CLI Reference/bom_validate.md
  docs/content/en/CLI Reference/bom_version.md
  docs/content/en/Contribution guidelines/_index.md
  docs/content/en/Quick Start/_index.md
  docs/content/en/Tutorials/_index.md
  docs/content/en/Tutorials/creating_bill_of_materials.md
  docs/content/en/Tutorials/using_yaml_config.md
  docs/content/en/_index.md
  docs/content/en/search.md
  docs/etcd-v3.4.16.spdx
  docs/go.mod
  docs/go.sum
  docs/package-lock.json
  docs/package.json
Labels: ok-to-test, lgtm, size/XXL, approved, cncf-cla: yes

#132 Remove feedback from docs
  .github/workflows/docs.yml
  docs/config.toml
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#133 New spdx+json parser!
  pkg/spdx/parser.go
  pkg/spdx/parser_unit_test.go
  pkg/spdx/spdx.go
  pkg/spdx/testdata/external-references.spdx.json
  pkg/spdx/testdata/images.spdx.json
Labels: kind/feature, lgtm, size/XXL, approved, cncf-cla: yes

#136 chore: use different base image to include go
  .ko.yaml
Labels: kind/bug, kind/feature, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#138 Don't concatenate name and version in os packages
  pkg/spdx/implementation.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#139 Disable local cache lookup, favor parallel download
  go.mod
  go.sum
  pkg/spdx/implementation.go
  pkg/spdx/spdx.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: kind/bug, lgtm, size/L, approved, cncf-cla: yes

#141 Add package url external ref in json format too
  pkg/serialize/serialize.go
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#143 Update image SBOMs to current practices
  pkg/spdx/implementation.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_unit_test.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#145 SPDX json definition set to minor version
  pkg/serialize/serialize.go
  pkg/spdx/json/v2.2/types.go
  pkg/spdx/parser.go
Labels: kind/api-change, ok-to-test, lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes
