Repository kubernetes-sigs/bom, pull requests merged in 2022-09, with the labels that each got.

#161 Fix license package to work with latest license classiffier
  go.mod
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/license_test.go
Labels: kind/bug, size/M, lgtm, approved, cncf-cla: yes

#162 Don't die if no go.sum file exists
  pkg/spdx/gomod.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#159 Workflow: Initial SPDX conformance check
  .github/workflows/verify-spdx.yaml
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#163 Fix file output with different format
  cmd/bom/cmd/generate.go
  pkg/spdx/builder.go
Labels: size/M, ok-to-test, lgtm, approved, cncf-cla: yes
