Repository kubernetes-sigs/bom, pull requests merged in 2022-11, with the labels that each got.

#190 Fix panic in outliner
  pkg/spdx/parser.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#191 Add checksums binaries
  magefile.go
  scripts/verify-build.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes

#173 Fix golang purls
  pkg/spdx/gomod.go
  pkg/spdx/gomod_test.go
Labels: ok-to-test, lgtm, size/S, approved, cncf-cla: yes

#199 replace the registry with cgr.dev
  .ko.yaml
Labels: kind/feature, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#200 Refactor file checksum fn
  pkg/spdx/object.go
Labels: size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#203 Fix b0rk when supplier is NOASSERTION
  pkg/spdx/parser.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes
