Repository kubernetes-sigs/bom, pull requests merged in 2022-10, with the labels that each got.

#170 Allow specifying URLs in `document outline/query`
  cmd/bom/cmd/document.go
  cmd/bom/cmd/query.go
  pkg/spdx/package_test.go
  pkg/spdx/parser.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#174 replace generate with version in CLI reference
  docs/content/en/CLI Reference/bom_version.md
Labels: ok-to-test, kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#175 Upgrade go1.19
  .github/dependabot.yml
  .github/workflows/docs.yml
  .github/workflows/verify-spdx.yaml
  .golangci.yml
  .ko.yaml
  cloudbuild.yaml
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/query.go
  go.mod
  magefile.go
  pkg/osinfo/layer_scanner.go
  pkg/query/filter.go
  pkg/spdx/file.go
  pkg/spdx/file_test.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/imageanalyzer_distroless.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_unit_test.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#189 Make license package more resilient to unexpected output
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/spdx/gomod.go
Labels: kind/bug, size/M, lgtm, kind/cleanup, approved, cncf-cla: yes
