Repository kubernetes-sigs/bom, pull requests merged in 2022-08, with the labels that each got.

#152 fix: ko version output
  magefile.go
Labels: kind/bug, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#153 fix check against the version that we need to install
  magefile.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#154 feat: use mage pkg to generate ldflags
  magefile.go
Labels: kind/feature, ok-to-test, lgtm, size/S, approved, cncf-cla: yes

#155 Fix create sbom tutorial link path in README.md
  README.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#156 Fix file type of compressed tars
  pkg/spdx/file.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#158 Introduce SPDX document interface
  pkg/spdx/json/document/document.go
  pkg/spdx/json/v2.2/types.go
  pkg/spdx/json/v2.3/types.go
  pkg/spdx/parser.go
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes

#160 fix generate command in tutorial doc
  docs/content/en/Tutorials/creating_bill_of_materials.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
