Repository kubernetes-sigs/bom, pull requests merged in 2022-02, with the labels that each got.

#58 Add validation for empty directories
  pkg/spdx/implementation.go
Labels: kind/bug, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#57 Make the document queryable (and ensure unique names)
  pkg/spdx/builder.go
  pkg/spdx/document.go
  pkg/spdx/document_unit_test.go
  pkg/spdx/file.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_unit_test.go
Labels: kind/bug, kind/feature, lgtm, size/L, approved, cncf-cla: yes

#46 Validate Subcommand!
  cmd/bom/cmd/root.go
  cmd/bom/cmd/validate.go
  go.mod
  go.sum
  pkg/spdx/document.go
  pkg/spdx/document_unit_test.go
  pkg/spdx/spdx.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#59 Add `ok-to-test` label to dependabot PRs
  .github/dependabot.yml
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#60 update version command to use the one from release-utils
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/root.go
  cmd/bom/cmd/version.go
  go.mod
  go.sum
  magefile.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes

#63 Support Parsing SBOMs from STDIN
  pkg/spdx/document.go
  pkg/spdx/file.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/parser.go
Labels: kind/bug, kind/feature, size/M, lgtm, kind/cleanup, approved, cncf-cla: yes
