Repository kubernetes-sigs/bom, pull requests merged in 2022-01, with the labels that each got.

#16 update license test by removing duplicate test file
  pkg/license/license_unit_test.go
  pkg/spdx/document_unit_test.go
Labels: size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#18 Enable generate on non-public, remote images
  pkg/spdx/implementation.go
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#20 small fixes in the code base
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  pkg/spdx/parser.go
Labels: lgtm, kind/cleanup, size/S, approved, cncf-cla: yes

#22 Fix a small typo in sbom guide
  docs/create-a-bill-of-materials.md
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#25 Fix flake in TestToProvenance and TestWriteProvenance
  pkg/spdx/document_unit_test.go
Labels: size/M, lgtm, kind/flake, kind/failing-test, approved, cncf-cla: yes

#24 replace references to --directory with --dirs
  docs/create-a-bill-of-materials.md
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#26 go imports update and fix mage build command
  go.mod
  magefile.go
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/license.go
  pkg/provenance/statement.go
  pkg/spdx/builder.go
  pkg/spdx/document_unit_test.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/object.go
  pkg/spdx/spdx_unit_test.go
  scripts/verify-build.sh
Labels: kind/feature, size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#27 add version command and ldflags
  cmd/bom/cmd/root.go
  cmd/bom/cmd/version.go
  magefile.go
  pkg/version/version.go
  pkg/version/version_test.go
  scripts/verify-build.sh
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#30 Fix "bom generate" command usage section in README
  README.md
Labels: size/M, ok-to-test, lgtm, approved, cncf-cla: yes

#31 Container Image Layer OS Scanner
  pkg/osinfo/container_scanner.go
  pkg/osinfo/container_scanner_test.go
  pkg/osinfo/layer_scanner.go
  pkg/osinfo/layer_scanner_test.go
  pkg/osinfo/testdata/dpkg-layer1.tar.gz
  pkg/osinfo/testdata/dpkg-layer2.tar.gz
  pkg/osinfo/testdata/link-with-dots.tar.gz
  pkg/osinfo/testdata/link-with-no-dots.tar.gz
  pkg/spdx/implementation.go
Labels: kind/feature, size/XL, lgtm, approved, cncf-cla: yes

#33 Add --archive and --image-archive usage in README
  docs/create-a-bill-of-materials.md
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#34 generate: Add --name --scan-images and check files early
  cmd/bom/cmd/generate.go
  pkg/spdx/builder.go
  pkg/spdx/implementation.go
  pkg/spdx/spdx.go
Labels: kind/bug, kind/feature, size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#37 Autodetect compressed tarballs and fix --scan-images flag
  pkg/osinfo/layer_scanner.go
  pkg/spdx/builder.go
  pkg/spdx/implementation.go
Labels: kind/bug, size/M, lgtm, approved, cncf-cla: yes

#39 Replace animation in main page with link to external player
  README.md
  docs/418528.svg
  docs/cast.svg
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes

#47 Disable cgo in build script
  scripts/verify-build.sh
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#50 builder: Support archives in config
  pkg/spdx/builder.go
Labels: kind/feature, lgtm, size/XS, approved, cncf-cla: yes

#51 generate: Print bom version when running
  cmd/bom/cmd/generate.go
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#54 Update and show help on missing file for outline subcommand
  cmd/bom/cmd/document.go
Labels: kind/bug, lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes
