Repository kubernetes-sigs/bom, pull requests merged in 2022-03, with the labels that each got.

#45 Add cloudbuild job to generate binaries and images
  .ko.yaml
  cloudbuild.yaml
  go.mod
  go.sum
  magefile.go
  pkg/osinfo/layer_scanner_test.go
  pkg/provenance/provenance.go
  pkg/spdx/document_unit_test.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#65 Fix image build command
  magefile.go
Labels: kind/bug, lgtm, kind/cleanup, size/S, approved, cncf-cla: yes

#67 update ko command
  cloudbuild.yaml
  magefile.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#66 feat: upgrade ko, utilize KOCACHE
  magefile.go
Labels: kind/feature, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#68 generate+document commands refactor
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/root.go
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes

#69 Generate purls from read sources
  go.mod
  go.sum
  pkg/osinfo/container_scanner.go
  pkg/osinfo/container_scanner_test.go
  pkg/osinfo/layer_scanner.go
  pkg/spdx/gomod.go
  pkg/spdx/gomod_test.go
  pkg/spdx/implementation.go
  pkg/spdx/package.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#73 fix: check local image cache first
  go.mod
  go.sum
  pkg/spdx/implementation.go
Labels: ok-to-test, lgtm, size/L, approved, cncf-cla: yes

#83 Add docs for YAML config
  docs/yaml_config.md
Labels: size/M, ok-to-test, kind/documentation, lgtm, approved, cncf-cla: yes

#84 Fix panic when emtpy os deps, readd document
  cmd/bom/cmd/document.go
  pkg/osinfo/container_scanner.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes
