Repository kubernetes-sigs/bom, pull requests merged in 2022-06, with the labels that each got.

#107 upgrade go to 1.18
  cloudbuild.yaml
  go.mod
  go.sum
  magefile.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#109 update github.com/google/go-containerregistry to v0.9.0
  README.md
  go.mod
  go.sum
  pkg/spdx/builder_unit_test.go
  pkg/spdx/implementation.go
  pkg/spdx/spdx_unit_test.go
Labels: kind/bug, lgtm, size/XXL, kind/cleanup, approved, cncf-cla: yes

#104 Add --format flag to output SPDX document as JSON
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/query.go
  pkg/query/engine.go
  pkg/query/expression.go
  pkg/query/expression_test.go
  pkg/query/filter.go
  pkg/query/filter_test.go
  pkg/serialize/serialize.go
  pkg/spdx/builder.go
  pkg/spdx/document.go
  pkg/spdx/document_unit_test.go
  pkg/spdx/file.go
  pkg/spdx/format.go
  pkg/spdx/json/v2.2.2/types.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/package_test.go
  pkg/spdx/spdx.go
  pkg/spdx/testdata/nginx.spdx
Labels: ok-to-test, lgtm, size/XXL, approved, cncf-cla: yes

#115 Replace pkg/errors dependency
  magefile.go
  pkg/provenance/predicate.go
  pkg/provenance/predicate_test.go
  pkg/provenance/provenance.go
  pkg/provenance/statement.go
  pkg/provenance/statement_test.go
Labels: size/M, ok-to-test, lgtm, kind/cleanup, approved, cncf-cla: yes

#116 cmd/bom: replace github.com/pkg/errors dependency with native error wrapping
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/query.go
  cmd/bom/cmd/validate.go
Labels: size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#117 pkg/osinfo: replace github.com/pkg/errors dependency with native error wrapping
  pkg/osinfo/container_scanner.go
  pkg/osinfo/layer_scanner.go
Labels: size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#118 pkg/query: replace github.com/pkg/errors dependency with native error wrapping
  pkg/query/engine.go
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#119 Fix import pkg/errors
  magefile.go
  pkg/provenance/predicate_test.go
  pkg/provenance/statement_test.go
Labels: ok-to-test, lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#120 replace error handling method in pkg/license
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/license/license_test.go
Labels: kind/bug, ok-to-test, lgtm, size/L, approved, cncf-cla: yes

#121 fix errors package used in pkg/license/catalog.go
  pkg/license/catalog.go
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#125 Bump github.com/google/licenseclassifier/v2 to v2.0.0-pre5
  go.mod
  go.sum
  pkg/license/implementation.go
Labels: lgtm, kind/cleanup, size/S, approved, cncf-cla: yes

#128 Revert "Bump github.com/google/licenseclassifier/v2 to v2.0.0-pre5"
  go.mod
  go.sum
  pkg/license/implementation.go
Labels: kind/bug, lgtm, kind/regression, size/S, approved, cncf-cla: yes

#123 Add dir verification support via `bom validate -d`
  cmd/bom/cmd/validate.go
  pkg/spdx/document.go
  pkg/spdx/parser.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes
