Repository kubernetes-sigs/bom, pull requests merged in 2022-12, with the labels that each got.

#211 Update owners
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, kind/cleanup, size/S, approved, cncf-cla: yes

#201 Download license zip instead of following links
  pkg/license/download.go
  pkg/license/implementation.go
Labels: ok-to-test, lgtm, size/L, approved, cncf-cla: yes

#212 Versions and purls in document outliner
  cmd/bom/cmd/document.go
  pkg/spdx/document.go
  pkg/spdx/package.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#213 Cache license network operations
  pkg/license/download.go
  pkg/license/license_unit_test.go
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/license/licensefakes/fake_reader_implementation.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes
