Repository kubernetes-sigs/bom, pull requests merged in 2023-03, with the labels that each got.

#241 Fix bug breaking license downloads
  pkg/license/catalog.go
  pkg/license/download.go
Labels: kind/bug, size/M, lgtm, approved, cncf-cla: yes

#244 Detect recursion loop in spdx.recursiveIDSearch
  pkg/spdx/spdx.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#243 Improve handling of 2.3 optional fields
  pkg/serialize/serialize.go
  pkg/spdx/implementation.go
  pkg/spdx/json/v2.2/types.go
  pkg/spdx/json/v2.3/types.go
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes

#224 Support for reading apk based distros
  go.mod
  go.sum
  pkg/osinfo/container_scanner.go
  pkg/osinfo/container_scanner_test.go
  pkg/osinfo/layer_scanner.go
  pkg/osinfo/testdata/apkdb
  pkg/spdx/implementation.go
Labels: kind/feature, lgtm, size/XXL, approved, cncf-cla: yes

#242 Change tool string to include version
  pkg/serialize/serialize.go
  pkg/spdx/document.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#245 Make license list version configurable
  cmd/bom/cmd/generate.go
  pkg/license/catalog.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/serialize/serialize.go
  pkg/spdx/builder.go
  pkg/spdx/builder_implementation.go
  pkg/spdx/document.go
  pkg/spdx/implementation.go
  pkg/spdx/spdx.go
Labels: kind/feature, size/XL, lgtm, approved, cncf-cla: yes

#249 update github.com/google/go-containerregistry to v0.14.0
  go.mod
  go.sum
  pkg/spdx/implementation.go
Labels: size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#250 Upgrade to go1.20
  .github/workflows/docs.yml
  .github/workflows/verify-spdx.yaml
  .ko.yaml
  cloudbuild.yaml
  go.mod
  magefile.go
Labels: kind/feature, size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#252 Update install instructions
  README.md
  docs/content/en/Quick Start/_index.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#255 Embed SPDX license list!
  magefile.go
  pkg/license/catalog.go
  pkg/license/data/license-list-v3.20.zip
  pkg/license/download.go
  pkg/license/license_test.go
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/license/licensefakes/fake_reader_implementation.go
Labels: kind/feature, tide/merge-method-squash, lgtm, size/L, approved, cncf-cla: yes

#257 refactor release
  .bom-config.yaml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .gitignore
  .goreleaser.yml
  cloudbuild.yaml
  go.mod
  go.sum
  magefile.go
  pkg/spdx/builder_implementation.go
  pkg/spdx/file.go
  pkg/spdx/gomod.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/package.go
Labels: kind/feature, lgtm, size/L, approved, cncf-cla: yes

#258 update release binary name
  .goreleaser.yml
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes
