Repository kubernetes-sigs/bom, pull requests merged in 2023-04, with the labels that each got.

#259 Keep reading SBOM until encoding is found
  pkg/spdx/document_unit_test.go
  pkg/spdx/parser.go
Labels: kind/bug, size/M, lgtm, kind/cleanup, approved, cncf-cla: yes

#260 Outliner: Autodetect open STDIN
  cmd/bom/cmd/document.go
  pkg/spdx/parser.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#270 OSInfo: Add support for download location
  pkg/osinfo/container_scanner.go
  pkg/spdx/implementation.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#269 Add Supplier Support in JSON encoded SBOMs
  pkg/osinfo/container_scanner_test.go
  pkg/serialize/serialize.go
  pkg/spdx/json/v2.2/types.go
  pkg/spdx/json/v2.3/types.go
Labels: kind/bug, size/M, lgtm, approved, cncf-cla: yes

#271 add attestation in the release job
  .github/workflows/release.yml
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes
