Repository kubernetes-sigs/bom, pull requests merged in 2023-09, with the labels that each got.

#329 Refactor osinfo Container Scanner
  pkg/osinfo/container_scanner.go
  pkg/osinfo/container_scanner_test.go
  pkg/osinfo/layer_scanner.go
  pkg/osinfo/layer_scanner_test.go
  pkg/osinfo/scanner_alpine.go
  pkg/osinfo/scanner_debian.go
  pkg/spdx/implementation.go
Labels: size/XL, lgtm, kind/cleanup, approved, cncf-cla: yes

#343 fix(osinfo): Fix package URL type for OS packages
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/osinfo/container_scanner.go
  pkg/osinfo/scanner_alpine.go
  pkg/osinfo/scanner_debian.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#345 OSInfo: Distroless Scanner
  pkg/osinfo/container_scanner.go
  pkg/osinfo/container_scanner_test.go
  pkg/osinfo/layer_scanner.go
  pkg/osinfo/scanner_debian.go
  pkg/osinfo/scanner_debian_test.go
  pkg/osinfo/scanner_distroless.go
  pkg/osinfo/scanner_distroless_test.go
  pkg/osinfo/scanner_rpm_test.go
  pkg/osinfo/testdata/distroless.tar
  pkg/spdx/implementation.go
  pkg/spdx/spdx_unit_test.go
Labels: kind/bug, kind/feature, size/XL, lgtm, approved, cncf-cla: yes

#346 fix(osinfo): Fix RPM version reporting
  pkg/osinfo/scanner_rpm.go
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes
