Repository kubernetes-sigs/bom, pull requests merged in 2023-10, with the labels that each got.

#350 Update Go to 1.21
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .github/workflows/verify-spdx.yaml
  .ko.yaml
  go.mod
  go.sum
  pkg/query/filter_test.go
  pkg/spdx/package_test.go
  pkg/spdx/spdx_unit_test.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#357 update license-data to v3.22
  pkg/license/data/README.md
  pkg/license/data/license-list-v3.22.zip
Labels: kind/feature, lgtm, size/XS, approved, cncf-cla: yes

#358 Trigger docs workflow on changes to workflow config file
  .github/workflows/docs.yml
Labels: kind/documentation, lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes
