Repository kubernetes-sigs/bom, pull requests merged in 2023-05, with the labels that each got.

#275 go.mod: Use uwu-tools/magex
  go.mod
  go.sum
  magefile.go
Labels: lgtm, kind/cleanup, size/S, approved, area/dependency, cncf-cla: yes

#289 update image naming scheme, compatibility with ggcr v0.15.2
  go.mod
  go.sum
  pkg/spdx/implementation.go
Labels: lgtm, size/L, kind/cleanup, approved, cncf-cla: yes

#291 document query improvements
  cmd/bom/cmd/document.go
  cmd/bom/cmd/document_outline.go
  cmd/bom/cmd/document_query.go
  cmd/bom/cmd/document_query_printers.go
  cmd/bom/cmd/query.go
  pkg/query/filter.go
  pkg/spdx/file.go
Labels: kind/feature, size/XL, lgtm, approved, cncf-cla: yes
