Repository kubernetes-sigs/bom, pull requests merged in 2024-07, with the labels that each got.

#462 Trim license patch from version tag, bump list to v3.24.0
  go.mod
  pkg/license/catalog.go
  pkg/license/data/license-list-v3.23.zip
  pkg/license/data/license-list-v3.24.0.zip
  pkg/spdx/builder_implementation.go
Labels: kind/bug, lgtm, kind/cleanup, kind/failing-test, size/S, approved, cncf-cla: yes

#452 Update golangci-lint and fix lints
  .golangci.yml
  cmd/bom/cmd/document_outline.go
  cmd/bom/cmd/document_query.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/root.go
  cmd/bom/cmd/validate.go
  go.mod
  go.sum
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/license_unit_test.go
  pkg/osinfo/container_scanner.go
  pkg/osinfo/container_scanner_test.go
  pkg/osinfo/layer_scanner.go
  pkg/osinfo/layer_scanner_test.go
  pkg/osinfo/scanner_alpine.go
  pkg/osinfo/scanner_debian.go
  pkg/osinfo/scanner_distroless.go
  pkg/osinfo/scanner_rpm.go
  pkg/provenance/predicate.go
  pkg/provenance/predicate_test.go
  pkg/provenance/predicate_unit_test.go
  pkg/provenance/provenance.go
  pkg/provenance/provenance_unit_test.go
  pkg/provenance/statement.go
  pkg/provenance/statement_test.go
  pkg/provenance/statement_unit_test.go
  pkg/query/engine.go
  pkg/query/filter.go
  pkg/query/filter_test.go
  pkg/serialize/serialize.go
  pkg/spdx/builder_implementation.go
  pkg/spdx/builder_unit_test.go
  pkg/spdx/document.go
  pkg/spdx/document_unit_test.go
  pkg/spdx/file.go
  pkg/spdx/gomod.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/imageanalyzer_distroless.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/package_test.go
  pkg/spdx/parser.go
  pkg/spdx/parser_unit_test.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_test.go
  pkg/spdx/spdx_unit_test.go
Labels: size/XL, lgtm, kind/cleanup, approved, cncf-cla: yes

#437 update java-spdx to 1.1.8
  .github/workflows/verify-spdx.yaml
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes
